### ISSUE TITLE
send to other server 

### ISSUE THREAD

**Issue by KhaledBasha** [corpix/smtpd#1]
how i can send email from this SMTP to other server like gmail ?

**Comment by corpix** [comment]
When `smtpd.Envelope` received in the `ServerSMTP` [handler](https://github.com/corpix/smtpd/blob/ffbc641407bd946d1c582b90050db37e87533120/examples/logging-smtpd/main.go#L16) any method could be used. For example you could google for `net/smtp` docs and find some useful examples like [this one](https://nathanleclaire.com/blog/2013/12/17/sending-email-from-gmail-using-golang/).

**Comment by corpix** [comment]
One thing that could cause frustration is `smtpd.Envelope.Data`. It contains [headers+message](https://github.com/corpix/smtpd/tree/2e35f13f5e0427831128958853209336ed7cbcb7#send-mail) and should be parsed. `net/mail.ReadMessage` [could be used](https://golang.org/pkg/net/mail/#ReadMessage) for this.
